apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: currency-bot-binding
spec:
  envFrom:
    - configMapRef:
        name: environment-properties
    - secretRef:
        name: secure-properties
  params:
    - name: branch
      value: $(params.target-branch)
    - name: target-branch
      value: $(params.target-branch)
    - name: type
      value: "currency-bot"
    - name: repository
      value: $(params.repository-url)
    - name: commit-id
      value: $(param.commit-id)
      default: ""
    - name: node-version
      value: "$(params.NODE_DEV_VERSION)"
      default: ""
    - name: npm-version
      value: $(params.npm-version)
      default: "" 
    - name: pl-name
      value: "currency-bot-$(params.node-version)"
    - name: pipeline-ref
      value: "currency-bot-pipeline"

---

apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: currency-bot-listener
spec:
  triggers:
    - bindings:
        - name: currency-bot-binding
      template:
        name: custom-template