apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: node-esm-binding
spec:
  envFrom:
    - configMapRef:
        name: environment-properties
  params:
    - name: branch
      value: $(params.target-branch)
    - name: target-branch
      value: $(params.target-branch)
    - name: type
      value: "esm"
    - name: repository
      value: $(params.repository-url)
    - name: commit-id
      value: $(param.commit-id)
      default: ""
    - name: node-version
      value: $(params.node-version)
      default: ""
    - name: npm-version
      value: $(params.npm-version)
      default: ""      
    - name: pl-name
      value: "esm-$(params.node-version)"
    - name: pipeline-ref
      value: "default-pipeline"
    - name: esm
      value: "true"

---

apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: node-esm-listener
spec:
  triggers:
    - bindings:
        - name: node-esm-binding
      template:
        name: custom-template