apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: main-binding
spec:
  envFrom:
    - configMapRef:
        name: environment-properties
  params:
    - name: branch
      value: "main"
    - name: target-branch
      value: "main"
    - name: type
      value: "main"
    - name: repository
      value: $(event.repository.html_url)
    - name: commit-id
      value: $(event.after)
    - name: node-version
      value: $(params.node-version)
      default: ""
    - name: npm-version
      value: $(params.npm-version)
      default: ""
    - name: pl-name
      value: $(event.after)
    - name: pipeline-ref
      value: "default-pipeline"
    - name: skip-cache
      value: $(params.skip-cache)
    - name: context
      value: "node-dev"
---

apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: main-listener
  annotations:
    pipeline.tekton.dev/max-concurrent-runs: "3"
spec:
  triggers:
    - bindings:
        - name: main-binding
      template:
        name: custom-template
