apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: node-x-manual-binding
spec:
  envFrom:
    - configMapRef:
        name: environment-properties
  params:
    - name: branch
      value: $(params.target-branch)
    - name: target-branch
      value: $(params.target-branch)
    - name: type
      value: "node-x-manual"
    - name: repository
      value: $(params.repository-url)
    - name: commit-id
      value: $(param.commit-id)
      default: ""
    - name: node-version
      value: $(params.node-version)
      default: ""
    - name: npm-version
      value: $(params.npm-version)
      default: ""
    - name: pl-name
      value: "manual-$(params.node-version)"
    - name: pipeline-ref
      value: "default-pipeline"
    - name: esm
      value: $(params.esm)
    - name: skip-cache
      value: $(params.skip-cache)
    - name: esm-suffix
      value: "$(params.esm == 'true' ? '-esm' : '')"
    - name: context
      value: "node-$(params.node-version)$(params.esm-suffix)"       

---

apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: node-x-manual-listener
spec:
  triggers:
    - bindings:
        - name: node-x-manual-binding
      template:
        name: custom-template