version: '2'
tasks:
  pr-code-checks:
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: npm-install
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail
          node_version="${node_version:-$(get_env node-version "$(get_env NODE_VERSION "")")}"
          curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          # shellcheck source=/dev/null
          . "$NVM_DIR/nvm.sh"
          nvm install "$node_version" --no-progress
          nvm use "$node_version"
          echo "Node.js: $(node --version)"

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts
          node bin/create-version-test-folders.js
      - name: sign-artifact
        when: 'false'
      - name: build-artifact
        when: 'false'
      - name: scan-artifact
        when: 'false'
  code-pr-finish:
    steps:
      - name: run-stage
        when: 'false'
  code-ci-finish:
    steps:
      - name: run-stage
        when: 'false'
  deploy-checks:
    when: false
  deploy-release:
    when: false
  pr-code-checks-audit:
    from: pr-code-checks
    displayName: audit
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: audit
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          npm run audit
      - name: sign-artifact
        when: 'false'
      - name: build-artifact
        when: 'false'
      - name: scan-artifact
        when: 'false'
  pr-code-checks-lint:
    from: pr-code-checks
    displayName: lint
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: lint
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          npm run lint
      - name: sign-artifact
        when: 'false'
      - name: build-artifact
        when: 'false'
      - name: scan-artifact
        when: 'false'
  pr-code-checks-commitlint:
    from: pr-code-checks
    displayName: commitlint
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: commitlint
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          npm run commitlint
      - name: sign-artifact
        when: 'false'
      - name: build-artifact
        when: 'false'
      - name: scan-artifact
        when: 'false'
  pr-code-checks-depcheck:
    from: pr-code-checks
    displayName: depcheck
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: depcheck
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          npm run depcheck
      - name: sign-artifact
        when: 'false'
      - name: build-artifact
        when: 'false'
      - name: scan-artifact
        when: 'false'
