version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: main
    ignore:
      - dependency-name: "@commitlint*"
      - dependency-name: "@types*"
      - dependency-name: "admin"
      - dependency-name: "admin-plugin-healthcheck"
      - dependency-name: "adm-zip"
      - dependency-name: "async"
      - dependency-name: "body-parser"
      - dependency-name: "chai*"
      - dependency-name: "basic-auth-parser"
      - dependency-name: "commitizen"
      - dependency-name: "cz-conventional-changelog"
      - dependency-name: "depcheck"
      - dependency-name: "dev-null"
      - dependency-name: "doctoc"
      - dependency-name: "eslint*"
      - dependency-name: "express-winston"
      - dependency-name: "husky"
      - dependency-name: "lerna"
      - dependency-name: "lodash"
      - dependency-name: "mkdirp"
      - dependency-name: "mocha*"
      - dependency-name: "mock-require"
      - dependency-name: "nyc"
      - dependency-name: "prettier"
      - dependency-name: "proxy*"
      - dependency-name: "read-pkg-up"
      - dependency-name: "recursive-copy"
      - dependency-name: "rimraf"
      - dependency-name: "sinon*"
      - dependency-name: "stealthy-require"
      - dependency-name: "superagent"
      - dependency-name: "typescript"
      - dependency-name: "underscore"
      - dependency-name: "uuid"
      - dependency-name: "wait-sync"
      - dependency-name: "yargs"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: weekly
    open-pull-requests-limit: 4
    # At times we might have 4 dependabot PRs open. Automatically rebasing
    # (which is the default) will trigger 4 CircleCI builds whenever we merge
    # something to main. This burns CircleCI credits pretty fast with little
    # benefit. Also, running multiple builds (for 4 branches) in parallel seems
    # make the CircleCI builds less stable. For these two reasons we disable
    # the automatic rebase. Instead, rebase manually when you want to merge
    # a dependabot PR.
    rebase-strategy: "disabled"
