version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: main
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "build:"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 5