version: '2'

tasks:
  # PR pipeline
  pr-code-checks:
    steps:
      - name: unit-test
        image: public.ecr.aws/docker/library/node:20
        script: |
          #!/bin/bash
          echo "Node: $(node --version)"
          echo "npm:  $(npm --version)"
          npm install --loglevel warn --foreground-scripts
          echo "npm install done."

  # CI pipeline
  code-build:
    steps:
      - name: unit-test
        image: public.ecr.aws/docker/library/node:20
        script: |
          #!/bin/bash
          echo "Node: $(node --version)"
          echo "npm:  $(npm --version)"
          npm install --loglevel warn --foreground-scripts
          echo "npm install done."
