version: '2'
tasks:
  pr-code-checks:
    steps:
      - name: run-stage
        when: 'false'
  pr-code-build:
    runtimeClassName: large
    steps:
      - name: build-artifact
        displayName: npm-install
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail
          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts
          node bin/create-version-test-folders.js
      - name: sign-artifact
        when: 'false'
  pr-code-build-core:
    from: pr-code-build
    displayName: core
    runtimeClassName: large
    steps:
      - name: build-artifact
        displayName: core
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          exec env -i \
            PATH="$PATH" \
            HOME="$HOME" \
            CI=true \
            npm run test:ci:core
      - name: sign-artifact
        when: 'false'
  app-preview-pr-finish:
    steps:
      - name: run-stage
        when: 'false'
