version: '2'
tasks:
  pr-code-checks:
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: npm-install
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail
          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts
          node bin/create-version-test-folders.js
  pr-code-checks-core:
    from: pr-code-checks
    displayName: core
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: core
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          exec env -i \
            PATH="$PATH" \
            HOME="$HOME" \
            CI=true \
            npm run test:ci:core
  pr-code-checks-metrics-util:
    from: pr-code-checks
    displayName: metrics-util
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: metrics-util
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          exec env -i \
            PATH="$PATH" \
            HOME="$HOME" \
            CI=true \
            npm run test:ci:metrics-util
  pr-code-checks-serverless:
    from: pr-code-checks
    displayName: serverless
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: serverless
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          exec env -i \
            PATH="$PATH" \
            HOME="$HOME" \
            CI=true \
            npm run test:ci:serverless
  pr-code-checks-serverless-collector:
    from: pr-code-checks
    displayName: serverless-collector
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: serverless-collector
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          exec env -i \
            PATH="$PATH" \
            HOME="$HOME" \
            CI=true \
            npm run test:ci:serverless-collector
  pr-code-checks-shared-metrics:
    from: pr-code-checks
    displayName: shared-metrics
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: shared-metrics
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          exec env -i \
            PATH="$PATH" \
            HOME="$HOME" \
            CI=true \
            npm run test:ci:shared-metrics
