version: '2'
tasks:
  code-checks:
    steps:
      - name: peer-review
        when: 'false'
  code-build:
    runtimeClassName: large
    steps:
      - name: build-artifact
        when: 'false'
      - name: unit-test
        when: 'false'
      - name: scan-artifact
        when: 'false'
      - name: sign-artifact
        when: 'false'
  sign-artifact:
    when: 'false'
  deploy-checks:
    when: 'false'
  deploy-release:
    when: 'false'
  code-ci-finish:
    steps:
      - name: run-stage
        when: 'false'
