version: '2'
tasks:
  pr-code-checks:
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: npm-install
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail
          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts
          node bin/create-version-test-folders.js
  pr-code-checks-opentelemetry-exporter:
    from: pr-code-checks
    displayName: opentelemetry-exporter
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: detect-secrets
        when: 'false'
      - name: compliance-checks
        when: 'false'
      - name: unit-test
        displayName: opentelemetry-exporter
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          exec env -i \
            PATH="$PATH" \
            HOME="$HOME" \
            CI=true \
            npm run test:ci:opentelemetry-exporter
