version: '2'
tasks:
  pr-code-checks:
    runtimeClassName: large
    steps:
      - name: run-stage
        displayName: npm-install
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail
          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts
          node bin/create-version-test-folders.js
  pr-code-checks-azure-container-services:
    from: pr-code-checks
    displayName: azure-container-services
    runtimeClassName: large
    steps:
      - name: run-stage
        displayName: azure-container-services
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          exec env -i \
            PATH="$PATH" \
            HOME="$HOME" \
            CI=true \
            npm run test:ci:azure-container-services
  code-pr-finish:
    steps:
      - name: run-stage
        when: 'false'
