version: '2'
tasks:
  pr-code-checks:
    steps:
      - name: run-stage
        when: 'false'
  pr-code-build:
    steps:
      - name: unit-test
        when: 'false'
      - name: build-artifact
        when: 'false'
      - name: scan-artifact
        when: 'false'
      - name: sign-artifact
        when: 'false'
  code-pr-finish:
    steps:
      - name: run-stage
        when: 'false'
