apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: custom-template
spec:
  envFrom:
    - configMapRef:
        name: environment-properties
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: branch
    - name: type
      description: type
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
      default: "0"
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: pr-branch
      description: The branch in the forked git repo from where the PR is made
    - name: pr-repository
      description: The branch in the forked git repo from where the PR is made
    - name: pr-number
      description: The branch in the forked git repo from where the PR is made
    - name: commit-id
      description: SHA
    - name: node-version
      value: $(params.node-version)
    - name: npm-version
      value: $(params.npm-version)
    - name: target-branch
      description: "Either pr branch or any other branch."
    - name: pl-name
      value: $(params.pl-name)
    - name: pipeline-ref
      value: $(params.pipeline-ref)
    - name: esm
      value: $(params.esm)
      default: "false"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pvc-$(params.target-branch)-$(uid)-artifacts
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: ConcurrencyControl
      metadata:
        name: cc
        namespace: concurrency
      spec:
        selector:
          matchLabels:
            type: pull-request
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      podTemplate:
        securityContext:
          fsGroup: 65532
      metadata:
        name: pl-$(params.target-branch)-$(params.pl-name)
        namespace: concurrency
        labels:
          type: pull-request
        annotations:
          tekton.dev/node-version: "node-$(params.node-version)"
      spec:
        pipelineRef:
          name: $(params.pipeline-ref)
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pvc-$(params.target-branch)-$(uid)-artifacts
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: pr-repository
            value: $(params.pr-repository)
          - name: pr-branch
            value: $(params.pr-branch)
          - name: pr-number
            value: $(params.pr-number)
          - name: commit-id
            value: $(params.commit-id)
          - name: node-version
            value: $(params.node-version)
          - name: npm-version
            value: $(params.npm-version)             
          - name: target-branch
            value: $(params.target-branch)
          - name: type
            value: $(params.type)
          - name: esm
            value: $(params.esm)