apiVersion: v1
kind: Service
metadata:
  name: eks-nodejs-inspector-service
  namespace: eks-sample-app
  labels:
    app: eks-nodejs-inspector-app
spec:
  selector:
    app: eks-nodejs-inspector-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
