apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-nodejs-inspector-deployment
  # Keeping this namespace because of the EKS Fargate profile namespace selector
  namespace: eks-sample-app
  labels:
    app: eks-nodejs-inspector-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-nodejs-inspector-app
  template:
    metadata:
      labels:
        app: eks-nodejs-inspector-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nodejs-inspector
        image: 410797082306.dkr.ecr.eu-west-1.amazonaws.com/fargate-eks-nodejs-inspector
        ports:
        - name: http
          containerPort: 3000
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
