# Bare Alpine image, native addon compilation will fail.
# They will be downloaded on demand at runtime.
# See Dockerfile.node-22.9.0-alpine-3.20-with-native for a Dockerfile that will
# build native addons successfully.

FROM node:22.9.0-alpine3.20

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production
COPY . .
EXPOSE 3333
CMD [ "npm", "start" ]
