# Bare Alpine image, native addon compilation WILL FAIL.
# See Dockerfile.node-14.9.0-alpine-3.11-with-native for a Dockerfile that will
# build native addons successfully.

FROM node:14.9.0-alpine3.11

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production
COPY . .
EXPOSE 3333
CMD [ "npm", "start" ]
