# Bare Alpine image, native addon compilation will fail.
# They will be downloaded on demand at runtime.
# See Dockerfile.node-v22-alpine-with-native for a Dockerfile that will
# build native addons successfully.

FROM node:22-alpine

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production
COPY . .
EXPOSE 3333
CMD [ "npm", "start" ]
