# Bare Node.js 22 image, using yarn.
# Native addons will work since the base image (Debian Buster) has all
# dependencies installed out of the box.

FROM node:22
WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn
COPY . .
EXPOSE 3333
CMD [ "yarn", "start" ]
