# An Alpine image with additional Alpine packages, so native addons can
# be compiled via node-gyp.

FROM node:22.9-alpine3.20
WORKDIR /usr/src/app
COPY package*.json ./

RUN apk add --no-cache --virtual .build-deps \
        build-base \
        python3 \
    && npm install --only=production \
    && apk del .build-deps

COPY . .
EXPOSE 3333
CMD [ "npm", "start" ]
