name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report. Please do not submit usage questions, support requests or feature requests here. Support requests need to be filed at [IBM's support portal](https://www.ibm.com/mysupport), while feature requests can be submitted via [IBM's ideas portal]<https://automation-management.ideas.ibm.com/?project=INSTANA>.

        Please also refrain from filing issues or support tickets if your audit tool (npm audit, Snyk, etc.) reported a CVE for a dependency of an Instana package -- we run these audits with every build and take appropriate action automatically.
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: What was the issue that caused you to file this bug?
    validations:
      required: true
  - type: input
    id: tracer-version
    attributes:
      label: Instana Node.js Tracer Version
      description: "Version of the Instana Node.js tracer affected by this bug"
      placeholder: v3.2.1
    validations:
      required: true
  - type: input
    id: nodejs-version
    attributes:
      label: Node.js Version
      description: Which version of Node.js are you using?
      placeholder: "v22.9.0"
    validations:
      required: true
  - type: textarea
    id: mcve
    attributes:
      label: Short, Self Contained Example
      description: Can you provide steps to reproduce this issue outside of your application? Or better yet, can you provide a [short, self contained reproducer](http://sscce.org/) as a zip file?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs & Error Messages
      description: "If possible please provide relevant logs, stack traces, or error messages."
    validations:
      required: false
  - type: textarea
    id: package-json
    attributes:
      label: package.json
      description: Please paste the contents of the package.json for the application that was affected by this bug.
      render: shell
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: "Tell us anything else you think we should know."
    validations:
      required: false

