apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: prepare-test-env
spec:
  params:
    - name: node-version
      value: $(params.node-version)
    - name: npm-version
      value: $(params.npm-version)
  workspaces:
    - name: output
      mountPath: /artifacts
  steps:
    - name: pre-cache-dependencies
      image: public.ecr.aws/docker/library/node:$(params.node-version)
      imagePullPolicy: IfNotPresent
      script: |
        #!/bin/bash

        ARTIFACTS_PATH="$(workspaces.output.path)"
        cd $ARTIFACTS_PATH

        mkdir -p .npm-offline-cache
        node bin/pre-cache-dependencies.js
    - name: generate-test-folders
      image: public.ecr.aws/docker/library/node:$(params.node-version)
      imagePullPolicy: IfNotPresent
      script: |
        #!/bin/bash

        ARTIFACTS_PATH="$(workspaces.output.path)"
        cd $ARTIFACTS_PATH

        if [ -n "$(params.npm-version)" ]; then
          npm install npm@$(params.npm-version) -g
        fi

        node bin/create-version-test-folders.js
