apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tasks-results-coverage
spec:
  workspaces:
    - name: output
      mountPath: /artifacts
  params:
    - name: properties-file
      default: build.properties
    - name: continuous-delivery-context-secret
      value: $(params.continuous-delivery-context-secret)      
  steps:
    - name: print-all-results
      image: ubuntu
      env:
        - name: PROPERTIES_FILE
          value: $(params.properties-file)
        - name: SONAR_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: "SONAR_TOKEN"          
        - name: SONAR_PWD
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: "SONAR_PWD"          
        - name: SONAR_LOGIN
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: "SONAR_LOGIN"          
      script: |
        #!/bin/bash
        
        ARTIFACTS_PATH="$(workspaces.output.path)"
        cd $ARTIFACTS_PATH

        if find "$ARTIFACTS_PATH" -maxdepth 1 -type f -name '*.failed' | grep -q .; then
          echo "PIPELINE_RESULT=Failed"
          echo "PIPELINE_RESULT=Failed" >> $ARTIFACTS_PATH/$PROPERTIES_FILE
        else
          echo "PIPELINE_RESULT=Succeeded"
          echo "PIPELINE_RESULT=Succeeded" >> $ARTIFACTS_PATH/$PROPERTIES_FILE          
        fi

        find ./coverage -name "*.json" -exec cp {} ./coverage/tmp \;
        npx c8 report --all --reporter=lcov

        npx eslint packages/ -f json > eslint-report.json || exit 0
        npx sonarqube-scanner