apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-artifacts-volume
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: team-nodejs-ci-shared-volume
  storageClassName: ibmc-vpc-block-retain-10iops-tier