apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-custom-storageclass
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  storage: 10Gi