apiVersion: v1
kind: PersistentVolume
metadata:
  name: team-nodejs-ci-shared-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ibmc-vpc-block-retain-10iops-tier
  hostPath:
    path: "/home/npm-cache"