apiVersion: v1
kind: PersistentVolume
metadata:
  name: repo-artifacts-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ibmc-vpc-block-retain-10iops-tier
  hostPath:
    path: "/home/artifcats"