version: '2'
tasks:
  code-build:
    runtimeClassName: large
    steps:
      - name: peer-review
        when: 'false'
      - name: unit-test
        displayName: currency-bot
        image: mirror.gcr.io/library/node:24
        script: |-
          #!/usr/bin/env bash
          set -eo pipefail

          GH_TOKEN="$(get_secret gh-public-token)"

          cd "$WORKSPACE/$(load_repo app-repo path)"
          npm install --loglevel warn --foreground-scripts

          git config user.name "Instanacd PAT for GitHub Public"
          git config user.email "instanacd@instana.com"

          # Install gh CLI and jq
          mkdir -p -m 755 /etc/apt/keyrings
          wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg \
            | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null
          chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] \
            https://cli.github.com/packages stable main" \
            | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          apt-get update -qq && apt-get install -y -qq gh jq

          echo "$GH_TOKEN" | gh auth login --with-token --hostname github.com

          OPEN_PRS=$(gh pr list --head currency-bot --base main --state open --json number | jq 'length')

          git ls-remote --exit-code --heads origin currency-bot >/dev/null 2>&1
          EXIT_CODE=$?

          if [[ $EXIT_CODE -eq 0 && $OPEN_PRS -eq 0 ]]; then
            echo "No open PRs found. Deleting branch currency-bot."
            git push origin --delete currency-bot
            EXIT_CODE=1
          fi

          if [[ $EXIT_CODE != 0 ]]; then
            echo "Running patch and minor updates..."
            MAJOR_UPDATES_MODE=false BRANCH=currency-bot node bin/dependencies/currency/update-currencies.js
          else
            echo "Open PRs exist for branch currency-bot. Skipping patch/minor updates."
          fi

          echo "Running major updates..."
          MAJOR_UPDATES_MODE=true BRANCH=currency-bot-major node bin/dependencies/currency/update-currencies.js
      - name: sign-artifact
        when: 'false'
      - name: build-artifact
        when: 'false'
      - name: scan-artifact
        when: 'false'
  sign-artifact:
    when: false
  deploy-checks:
    when: false
  deploy-release:
    when: false
  code-ci-finish:
    steps:
      - name: run-stage
        when: 'false'
  code-checks:
    when: false
