---

resources:

  - name: nodejs-repository
    type: git
    icon: github
    source:
      uri: https://github.com/instana/nodejs.git
      branch: node20-dev
      username: ((instanacd-github-api-token))
      password: x-oauth-basic


  - name: instana-aws-fargate-npm-package
    type: npm-resource
    icon: cube-outline
    source:
      scope: instana
      package: aws-fargate
      registry:
        uri: https://registry.npmjs.org/

resource_types:

  - name: npm-resource
    type: registry-image
    source:
      repository: timotto/concourse-npm-resource
      tag: latest

jobs:

  # self-update is only important for the the production system!

  - name: aws-fargate-nodejs-container-image-layer
    serial: true
    plan:
      - in_parallel:
        - get: instana-aws-fargate-npm-package
          trigger: true
          params:
            skip_download: true
        - get: nodejs-repository

      - load_var: package-version
        file: instana-aws-fargate-npm-package/version
        reveal: true

      - load_var: nodejs-version
        file: nodejs-repository/.nvmrc
        reveal: true

      - task: build-fargate-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
              tag: latest
          params:
            CONTEXT: nodejs-repository/packages/aws-fargate/images/instana-aws-fargate/
            DOCKERFILE: nodejs-repository/packages/aws-fargate/images/instana-aws-fargate/Dockerfile-npm
            BUILD_ARG_package_version: ((.:package-version))
            BUILD_ARG_NODEJS_VERSION: ((.:nodejs-version))
          inputs:
            - name: nodejs-repository
          outputs:
            - name: image
          run:
            path: build
