apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: simple-echo-pipeline-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: "pr-run-"
      spec:
        taskSpec:
          steps:
            - name: debug-step
              image: ubuntu
              script: |
                echo "Params: $(params)"
            - name: echo-step
              image: ubuntu
              script: echo "hello there"
---

apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: event-binding
spec:
  params:
    - name: branch
      value: $(event.pull_request.base.ref)
    - name: target-branch
      value: $(event.pull_request.base.ref)
    - name: commit-id
      value: $(event.pull_request.head.sha)
    - name: commit-timestamp
      value: $(event.pull_request.head.repo.pushed_at)
    - name: target-commit-id
      value: $(event.pull_request.base.sha)
    - name: pr-url
      value: $(event.pull_request.url)
    - name: pr-number
      value: $(event.pull_request.number)
    - name: pr-name
      value: $(event.pull_request.user.login)
    - name: repository
      value: $(event.repository.html_url)
    - name: scm-type
      value: "github-ent"
    - name: pr-repository
      value: $(event.pull_request.head.repo.html_url)
    - name: pr-branch
      value: $(event.pull_request.head.ref)

---

apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: simple-echo-pipeline-listener
spec:
  triggers:
  - name: "my-trigger"
    bindings:
    - ref: event-binding
    template:
      name: simple-echo-pipeline-template