apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: branch
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: target-branch
      description: target branch
    - name: commit-id
      description: commit id
    - name: commit-timestamp
      description: commit timestamp
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: pr-url
      description: pr url
    - name: target-commit-id
      description: target branch commit id
    - name: project-id
      description: project id
      default: ""
    - name: scm-type
      description: source code type used (github, github-ent, gitlab)
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: tf-dir
      description: the directory where the terraform main entry file is found
      default: ""
    - name: policy-config-json
      description: Configure policies to control thresholds
      default: ""
    - name: tf-var-file
      description: (optional) terraform var-file
      default: ""
    - name: pr-repository
      value: $(params.pr-repository)
    - name: pr-branch
      value: $(params.pr-branch)
  workspaces:
    - name: artifacts

  tasks:
    - name: extract-repository-url
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          # if a params.repository is given, it takes precedence
          value: '. as $toolchain | ["$(params.repository)"] | if .[0]=="" then $toolchain | .services[] | select(.toolchain_binding.name=="repo") | .dashboard_url else .[0] end'
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: git-fetch-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: branch
          value: $(params.branch)
        - name: revision
          value: $(params.revision)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: pr-repository
          value: $(params.pr-repository)
        - name: pr-branch
          value: $(params.pr-branch)
      workspaces:
        - name: output
          workspace: artifacts

---

apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pr-template
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: branch
    - name: target-branch
      description: target branch
    - name: target-commit-id
      description: target commit id
    - name: apikey
      description: the ibmcloud api key
    - name: commit-id
      description: commit id
    - name: commit-timestamp
      description: commit timestamp
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
      default: "0"
    - name: pr-url
      description: PR url
    - name: scm-type
      description: source code type used (github, github-ent, gitlab)
    - name: project-id
      description: project id
      default: ""
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: tf-dir
      description: the directory where the terraform main entry file is found
    - name: policy-config-json
      description: Configure policies to control thresholds
    - name: tf-var-file
      description: (optional) terraform var-file
    - name: pr-repository
      description: The forked git repo from where the PR is made
    - name: pr-branch
      description: The branch in the forked git repo from where the PR is made
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pr-pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: target-branch
            value: $(params.target-branch)
          - name: commit-id
            value: $(params.commit-id)
          - name: commit-timestamp
            value: $(params.commit-timestamp)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: pr-url
            value: $(params.pr-url)
          - name: target-commit-id
            value: $(params.target-commit-id)
          - name: scm-type
            value: $(params.scm-type)
          - name: project-id
            value: $(params.project-id)
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: tf-dir
            value: $(params.tf-dir)
          - name: policy-config-json
            value: $(params.policy-config-json)
          - name: tf-var-file
            value: $(params.tf-var-file)
          - name: pr-repository
            value: $(params.pr-repository)
          - name: pr-branch
            value: $(params.pr-branch)
---

apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
    - name: branch
      value: $(event.pull_request.base.ref)
    - name: target-branch
      value: $(event.pull_request.base.ref)
    - name: commit-id
      value: $(event.pull_request.head.sha)
    - name: commit-timestamp
      value: $(event.pull_request.head.repo.pushed_at)
    - name: target-commit-id
      value: $(event.pull_request.base.sha)
    - name: pr-url
      value: $(event.pull_request.url)
    - name: pr-number
      value: $(event.pull_request.number)
    - name: pr-name
      value: $(event.pull_request.user.login)
    - name: repository
      value: $(event.repository.html_url)
    - name: scm-type
      value: "github-ent"
    - name: pr-repository
      value: $(event.pull_request.head.repo.html_url)
    - name: pr-branch
      value: $(event.pull_request.head.ref)

---

apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-pr-listener
spec:
  triggers:
    - bindings:
      - name: github-pr-binding
    template:
      name: pr-template