apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tasks-results
spec:
  params:
    - name: test1
      value: $(params.test1)
    - name: test2
      value: $(params.test2)
  workspaces:
    - name: output
      mountPath: /artifacts
  steps:
    - name: print-all-results
      image: ubuntu
      script: |
        #!/bin/bash

        test1="$(params.test1)"
        test2="$(params.test2)"

        if [ "$test1" == "Succeeded" ] && [ "$test2" == "Succeeded" ]; then
            echo "All tests passed".
            exit 0
        else
            echo "Tests failed."
            exit 1
        fi