name: Generate SonarQube Report
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: sonarqube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # You can specify your preferred Node.js version here
      - name: Install dependencies
        run: npm ci
      - name: Run tests and generate coverage
        run: |
          # Run tests in all packages using Lerna
          npx lerna run test --stream

          # Generate Jest coverage reports in JSON format for each package
          npx lerna exec -- npx jest --coverage --coverageReporters=json
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}